### PR TITLE
Create benchmark script

### PR DESCRIPTION
**Pull request by abelsiqueira**
Create a benchmark script.
@manuelma @Tasqu, @suvayu and I created this simple benchmark using the first test in run_spineopt.jl.
However, this is not substantial enough.
Can you

- suggest improvements to make it more substantial; and/or
- share some data in sqlite format?

Thanks in advance.

## Checklist before merging
- [x] Documentation is up-to-date
- [x] Unit tests have been added/updated accordingly
- [x] Code has been formatted according to SpineOpt's style
- [x] Unit tests pass

### CODE REVIEW

**Comment by abelsiqueira** [comment]
@tarskul, maybe you can help us with data?

**Comment by manuelma** [comment]
[run_spineopt_benchmarks.zip](https://github.com/spine-tools/SpineOpt.jl/files/14507651/run_spineopt_benchmarks.zip)
@abelsiqueira I was working on something before, here it is for inspiration?

**Comment by tarskul** [comment]
I'm currently working on a workflow with data from PyPSA, converting it to the ines-spec and then using that to run a model in PyPSA and SpineOpt as a comparison benchmark. Once I have a small working example (it may take a few weeks as I cannot always allocate time for this), I'll share that and I'll be able to help with data or the benchmarking itself. If you cannot wait, you can find data for/from PyPSA on Zenodo.

**Comment by abelsiqueira** [comment]
Thanks @manuelma, we've used your example and changed our script.
It should be a good benchmark to start, so we think it's ready to merge.

We haven't added any automation to this for simplicity. We can create a new issue for that, if you want.

**Comment by abelsiqueira** [comment]
By the way, this warning came up:

```
┌ Warning: no objective terms defined
└ @ SpineOpt ~/projects/work/MOPO/SpineOpt.jl/src/run_spineopt_standard.jl:229
```

**Comment by abelsiqueira** [comment]
@tarskul, thanks, it might be useful later, maybe in addition to the example given by @manuelma. For now, we have enough for this issue, but we can revisit in a few weeks.

**Review by clizbe — APPROVED** [review]
LGTM!

**Pull request merged**
