### PR TITLE
Add multi year investment tutorial

### LINKED ISSUE #1041: Change temporal structure for investment and operation blocks in multi-year investments
Implement changes proposed in Discussion #1039

### PR DESCRIPTION
**Pull request by gnawin**
(description of changes)

Fixes #1041 

## Checklist before merging
- [x] Documentation is up-to-date
- [x] Unit tests have been added/updated accordingly
- [x] Code has been formatted according to SpineOpt's style
- [x] Unit tests pass

### CODE REVIEW

**Comment by tarskul** [comment]
There was a tutorial missing on capacity planning. That is now in the works (#1049). This tutorial should build on that. Both tutorials are perhaps even small enough to be combined into one.

**Comment by tarskul** [comment]
Ah, uhm, I already merged it to master. But don't worry, I'll combine them later. Is this branch based on master or an experimental branch? If it is based on master, I can merge master into add-multi-year-tutorial and then combine the tutorials.

**Comment by gnawin** [comment]
No worries. It is based on master (after your recent doc overhaul at least).

**Comment by gnawin** [comment]
@tarskul I added the missing figures. You may want to merge this after you align with the other tutorial. 

Or maybe it is more convenient if we keep both for now, and do something later because they talk about slightly different topics, and I can soon expand this tutorial with more economic representations. If so, I'll just add a reference to the other tutorial and merge this.

**Comment by tarskul** [comment]
@gnawin In a local branch I'm trying to combine the two tutorials as they are both about capacity planning. I'll see how that goes. But if more tutorials are coming, we should perhaps list them in #735 such that we have an overview and can see what would fit where exactly. If there are indeed many things they could perhaps become an 'advanced' tutorial. We'll see.

**Comment by gnawin** [comment]
Cool! There will not be more tutorials from my side, but my plan is to populate this tutorial by adding more stuff about using economic parameters. I can start populate once this has been merged.

**Comment by tarskul** [comment]
This is what I have so far. I think it works as a tutorial. I'll just have to try the tutorial myself and see whether it also actually runs.

If that is ok with you, then we may ship it soon.

As for the other economic parameters, let's discuss them at some point to see whether it makes more sense to add them to this tutorial or to make a separate tutorial for them.

**Comment by gnawin** [comment]
Yes, if everything works, you can merge this.

**Review by tarskul — APPROVED** [review]

**Pull request merged**
